engine:
  type: "in_memory"
  partitions_number: 8
wal:
  flushing_batch_length: 100
  flushing_batch_timeout: "10ms"
  max_segment_size: "1KB"
  data_directory: "./local_test/wal"
network:
  address: "127.0.0.1:3223"
  max_connections: 100
  max_message_size: "4KB"
  idle_timeout: 5m
logging:
  level: "debug"
  output: "./local_test/log/output.log"